name: Mirror To Epitech Repository

on: push

jobs:
  PushToEpitech:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1.0.1
        if: github.repository == '0Nom4D/309pollution'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        with:
          source-repo: git@github.com:0Nom4D/308reedpipes.git
          destination-repo: git@github.com:EpitechPromo2024/B-MAT-500-NAN-5-1-309pollution-arthur.adam.git